version: '3.8'

services:
  backend:
    image: runner-backend:latest
    ports:
      - "8000:8000"
    networks:
      - frontend-net
      - backend-db-net
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DBUSER=devuser
      - DBPASSWORD=devpass
      - DBNAME=devdb
    depends_on:
      - db

  frontend:
    image: runner-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - frontend-net
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - backend

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB=devdb
      POSTGRES_USER=devuser
      POSTGRES_PASSWORD=devpass
    networks:
      - backend-db-net
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  frontend-net:
    driver: bridge
  backend-db-net:
    driver: bridge

volumes:
  db-data:
