# 実行環境の制限設定

# 1分間に許可する最大リクエスト数（DoS対策・同時利用制限）
rate_limit_per_minute: 30  # 例: 30回/分

# 1リクエストあたりの最大コード長（文字数）
max_code_length: 10000  # 例: 10000文字

# 標準出力の最大バイト数（超過時はカットしexit_code=1002）
max_stdout_bytes: 1048576  # 例: 1MB = 1048576

# 標準エラー出力の最大バイト数（超過時はカットしexit_code=1002）
max_stderr_bytes: 1048576  # 例: 1MB = 1048576

# 1回の実行の最大許容時間（秒、超過時は強制終了・exit_code=1001）
max_exec_time: 10  # 例: 10秒

# 1リクエストあたりの最大リクエストボディサイズ（バイト）
max_request_body_size: 1048576  # 例: 1MB = 1048576

# コンテナに割り当てる最大メモリ量（Dockerのmem_limit形式）
mem_limit: 512m  # 例: 512m, 1g

# コンテナに割り当てる最大CPUコア数（1.0=1コア、0.5=半コア）
cpu_limit: 1.0  # 例: 1.0, 0.5
